# 今回使うDockerの参照元のイメージ
FROM ruby:3.3.6

# なんやかんやおまじない
ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

# node.jsやyarnをインストール
RUN apt-get update -qq \
&& apt-get install -y ca-certificates curl gnupg \
&& mkdir -p /etc/apt/keyrings \
&& curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
&& NODE_MAJOR=20 \
&& echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
&& wget --quiet -O - /tmp/pubkey.gpg https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
&& echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs yarn vim

# 作業ディレクトリ
RUN mkdir /myapp
WORKDIR /myapp

# bundler を先に入れる
RUN gem install bundler

# Gemfile と package.json を先にコピーして依存関係をキャッシュ
COPY Gemfile Gemfile.lock /myapp/
COPY package.json yarn.lock /myapp/

# Ruby と JavaScript の依存関係をインストール
RUN bundle install
RUN yarn install

# 最後にアプリ全体をコピー
COPY . /myapp